name: 'Repository Webhooks'
description: 'Get repository webhooks'

inputs:
  org:
    description: 'Organization name'
    required: true

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }}
      shell: bash
      working-directory: ./repository/webhooks
