name: 'Organization GitHub Actions History'
description: 'Get Organization GitHub Actions History'

inputs:
  org:
    description: 'Organization name'
    required: true

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }}
      shell: bash
      working-directory: ./organization/actions-history
