name: 'Repository Branch Protection Rules'
description: 'Get repository branch protection rules'

inputs:
  org:
    description: 'Organization name'
    required: true

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.org }}
      shell: bash
      working-directory: ./repository/branch-protection-rules
