name: Cleanup Workflow Runs

on:
  workflow_dispatch:

jobs:
  do:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Cleanup Workflow Runs
        run: gh run list --json databaseId --jq '.[].databaseId' | xargs -n1 -I % gh run delete %
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
